# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/glitchedcode/repos/WallPin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/glitchedcode/repos/WallPin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/glitchedcode/repos/WallPin/CMakeFiles /home/glitchedcode/repos/WallPin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/glitchedcode/repos/WallPin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wallpin

# Build rule for target.
wallpin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wallpin
.PHONY : wallpin

# fast build rule for target.
wallpin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/build
.PHONY : wallpin/fast

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/config.c.s
.PHONY : src/config.c.s

src/layer_shell.o: src/layer_shell.c.o
.PHONY : src/layer_shell.o

# target to build an object file
src/layer_shell.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/layer_shell.c.o
.PHONY : src/layer_shell.c.o

src/layer_shell.i: src/layer_shell.c.i
.PHONY : src/layer_shell.i

# target to preprocess a source file
src/layer_shell.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/layer_shell.c.i
.PHONY : src/layer_shell.c.i

src/layer_shell.s: src/layer_shell.c.s
.PHONY : src/layer_shell.s

# target to generate assembly for a file
src/layer_shell.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/layer_shell.c.s
.PHONY : src/layer_shell.c.s

src/layout.o: src/layout.c.o
.PHONY : src/layout.o

# target to build an object file
src/layout.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/layout.c.o
.PHONY : src/layout.c.o

src/layout.i: src/layout.c.i
.PHONY : src/layout.i

# target to preprocess a source file
src/layout.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/layout.c.i
.PHONY : src/layout.c.i

src/layout.s: src/layout.c.s
.PHONY : src/layout.s

# target to generate assembly for a file
src/layout.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/layout.c.s
.PHONY : src/layout.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/main.c.s
.PHONY : src/main.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/wallpaper.o: src/wallpaper.c.o
.PHONY : src/wallpaper.o

# target to build an object file
src/wallpaper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/wallpaper.c.o
.PHONY : src/wallpaper.c.o

src/wallpaper.i: src/wallpaper.c.i
.PHONY : src/wallpaper.i

# target to preprocess a source file
src/wallpaper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/wallpaper.c.i
.PHONY : src/wallpaper.c.i

src/wallpaper.s: src/wallpaper.c.s
.PHONY : src/wallpaper.s

# target to generate assembly for a file
src/wallpaper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wallpin.dir/build.make CMakeFiles/wallpin.dir/src/wallpaper.c.s
.PHONY : src/wallpaper.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... wallpin"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/layer_shell.o"
	@echo "... src/layer_shell.i"
	@echo "... src/layer_shell.s"
	@echo "... src/layout.o"
	@echo "... src/layout.i"
	@echo "... src/layout.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/wallpaper.o"
	@echo "... src/wallpaper.i"
	@echo "... src/wallpaper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

